usr/share/themes/Ambiant-MATE-Aqua usr/share/themes/
usr/share/themes/Ambiant-MATE-Dark-Aqua usr/share/themes/
usr/share/themes/Radiant-MATE-Aqua usr/share/themes/

usr/share/icons/Ambiant-MATE-Aqua usr/share/icons/
usr/share/icons/Radiant-MATE-Aqua usr/share/icons/

backgrounds/ubuntu-mate-aqua usr/share/backgrounds/
mate-background-properties/ubuntu-mate-aqua.xml /usr/share/mate-background-properties/
