usr/share/themes/Ambiant-MATE-Teal usr/share/themes/
usr/share/themes/Ambiant-MATE-Dark-Teal usr/share/themes/
usr/share/themes/Radiant-MATE-Teal usr/share/themes/

usr/share/icons/Ambiant-MATE-Teal usr/share/icons/
usr/share/icons/Radiant-MATE-Teal usr/share/icons/

backgrounds/ubuntu-mate-teal usr/share/backgrounds/
mate-background-properties/ubuntu-mate-teal.xml /usr/share/mate-background-properties/
