usr/share/themes/Ambiant-MATE-Orange usr/share/themes/
usr/share/themes/Ambiant-MATE-Dark-Orange usr/share/themes/
usr/share/themes/Radiant-MATE-Orange usr/share/themes/

usr/share/icons/Ambiant-MATE-Orange usr/share/icons/
usr/share/icons/Radiant-MATE-Orange usr/share/icons/

backgrounds/ubuntu-mate-orange usr/share/backgrounds/ubuntu-mate-orange
mate-background-properties/ubuntu-mate-orange.xml /usr/share/mate-background-properties/
