usr/share/themes/Ambiant-MATE-Blue usr/share/themes/
usr/share/themes/Ambiant-MATE-Dark-Blue usr/share/themes/
usr/share/themes/Radiant-MATE-Blue usr/share/themes/

usr/share/icons/Ambiant-MATE-Blue usr/share/icons/
usr/share/icons/Radiant-MATE-Blue usr/share/icons/

usr/share/themes/Yaru-MATE-Blue-light usr/share/themes/
usr/share/themes/Yaru-MATE-Blue-dark usr/share/themes/

usr/share/icons/Yaru-MATE-Blue-light usr/share/icons/
usr/share/icons/Yaru-MATE-Blue-dark usr/share/icons/

usr/share/backgrounds/ubuntu-mate-colours-blue/
usr/share/mate-background-properties/ubuntu-mate-colours-blue.xml
usr/share/plank/themes/Ubuntu-MATE-Blue/dock.theme
