usr/share/themes/Ambiant-MATE-Blue usr/share/themes/
usr/share/themes/Ambiant-MATE-Dark-Blue usr/share/themes/
usr/share/themes/Radiant-MATE-Blue usr/share/themes/

usr/share/icons/Ambiant-MATE-Blue usr/share/icons/
usr/share/icons/Radiant-MATE-Blue usr/share/icons/

backgrounds/ubuntu-mate-blue usr/share/backgrounds/ubuntu-mate-blue
mate-background-properties/ubuntu-mate-blue.xml /usr/share/mate-background-properties/
