usr/share/themes/Ambiant-MATE-Yellow usr/share/themes/
usr/share/themes/Ambiant-MATE-Dark-Yellow usr/share/themes/
usr/share/themes/Radiant-MATE-Yellow usr/share/themes/

usr/share/icons/Ambiant-MATE-Yellow usr/share/icons/
usr/share/icons/Radiant-MATE-Yellow usr/share/icons/

usr/share/backgrounds/ubuntu-mate-colours-yellow/
usr/share/mate-background-properties/ubuntu-mate-colours-yellow.xml
usr/share/plank/themes/Ubuntu-MATE-Yellow/dock.theme
