usr/share/themes/Ambiant-MATE-Brown usr/share/themes/
usr/share/themes/Ambiant-MATE-Dark-Brown usr/share/themes/
usr/share/themes/Radiant-MATE-Brown usr/share/themes/

usr/share/icons/Ambiant-MATE-Brown usr/share/icons/
usr/share/icons/Radiant-MATE-Brown usr/share/icons/

usr/share/backgrounds/ubuntu-mate-colours-brown/
usr/share/mate-background-properties/ubuntu-mate-colours-brown.xml
usr/share/plank/themes/Ubuntu-MATE-Brown/dock.theme
