usr/share/themes/Ambiant-MATE-Yellow usr/share/themes/
usr/share/themes/Ambiant-MATE-Dark-Yellow usr/share/themes/
usr/share/themes/Radiant-MATE-Yellow usr/share/themes/

usr/share/icons/Ambiant-MATE-Yellow usr/share/icons/
usr/share/icons/Radiant-MATE-Yellow usr/share/icons/

backgrounds/ubuntu-mate-yellow usr/share/backgrounds/
mate-background-properties/ubuntu-mate-yellow.xml /usr/share/mate-background-properties/
