usr/share/themes/Ambiant-MATE-Teal usr/share/themes/
usr/share/themes/Ambiant-MATE-Dark-Teal usr/share/themes/
usr/share/themes/Radiant-MATE-Teal usr/share/themes/

usr/share/icons/Ambiant-MATE-Teal usr/share/icons/
usr/share/icons/Radiant-MATE-Teal usr/share/icons/

usr/share/themes/Yaru-MATE-Teal-light usr/share/themes/
usr/share/themes/Yaru-MATE-Teal-dark usr/share/themes/

usr/share/icons/Yaru-MATE-Teal-light usr/share/icons/
usr/share/icons/Yaru-MATE-Teal-dark usr/share/icons/

usr/share/backgrounds/ubuntu-mate-colours-teal/
usr/share/mate-background-properties/ubuntu-mate-colours-teal.xml
usr/share/plank/themes/Ubuntu-MATE-Teal/dock.theme
