usr/share/themes/Ambiant-MATE-Orange usr/share/themes/
usr/share/themes/Ambiant-MATE-Dark-Orange usr/share/themes/
usr/share/themes/Radiant-MATE-Orange usr/share/themes/

usr/share/icons/Ambiant-MATE-Orange usr/share/icons/
usr/share/icons/Radiant-MATE-Orange usr/share/icons/

usr/share/themes/Yaru-MATE-Orange-light usr/share/themes/
usr/share/themes/Yaru-MATE-Orange-dark usr/share/themes/

usr/share/icons/Yaru-MATE-Orange-light usr/share/icons/
usr/share/icons/Yaru-MATE-Orange-dark usr/share/icons/

usr/share/backgrounds/ubuntu-mate-colours-orange/
usr/share/mate-background-properties/ubuntu-mate-colours-orange.xml
usr/share/plank/themes/Ubuntu-MATE-Orange/dock.theme
