usr/share/themes/Ambiant-MATE-Pink usr/share/themes/
usr/share/themes/Ambiant-MATE-Dark-Pink usr/share/themes/
usr/share/themes/Radiant-MATE-Pink usr/share/themes/

usr/share/icons/Ambiant-MATE-Pink usr/share/icons/
usr/share/icons/Radiant-MATE-Pink usr/share/icons/

usr/share/themes/Yaru-MATE-light-Pink usr/share/themes/
usr/share/themes/Yaru-MATE-dark-Pink usr/share/themes/

usr/share/icons/Yaru-MATE-light-Pink usr/share/icons/
usr/share/icons/Yaru-MATE-dark-Pink usr/share/icons/

usr/share/backgrounds/ubuntu-mate-colours-pink/
usr/share/mate-background-properties/ubuntu-mate-colours-pink.xml
usr/share/plank/themes/Ubuntu-MATE-Pink/dock.theme
