usr/share/themes/Ambiant-MATE-Purple usr/share/themes/
usr/share/themes/Ambiant-MATE-Dark-Purple usr/share/themes/
usr/share/themes/Radiant-MATE-Purple usr/share/themes/

usr/share/icons/Ambiant-MATE-Purple usr/share/icons/
usr/share/icons/Radiant-MATE-Purple usr/share/icons/

backgrounds/ubuntu-mate-purple usr/share/backgrounds/
mate-background-properties/ubuntu-mate-purple.xml /usr/share/mate-background-properties/
