usr/share/themes/Ambiant-MATE-Red usr/share/themes/
usr/share/themes/Ambiant-MATE-Dark-Red usr/share/themes/
usr/share/themes/Radiant-MATE-Red usr/share/themes/

usr/share/icons/Ambiant-MATE-Red usr/share/icons/
usr/share/icons/Radiant-MATE-Red usr/share/icons/

usr/share/themes/Yaru-MATE-light-Red usr/share/themes/
usr/share/themes/Yaru-MATE-dark-Red usr/share/themes/

usr/share/icons/Yaru-MATE-light-Red usr/share/icons/
usr/share/icons/Yaru-MATE-dark-Red usr/share/icons/

usr/share/backgrounds/ubuntu-mate-colours-red/
usr/share/mate-background-properties/ubuntu-mate-colours-red.xml
usr/share/plank/themes/Ubuntu-MATE-Red/dock.theme
