usr/share/themes/Ambiant-MATE-Pink usr/share/themes/
usr/share/themes/Ambiant-MATE-Dark-Pink usr/share/themes/
usr/share/themes/Radiant-MATE-Pink usr/share/themes/

usr/share/icons/Ambiant-MATE-Pink usr/share/icons/
usr/share/icons/Radiant-MATE-Pink usr/share/icons/

backgrounds/ubuntu-mate-pink usr/share/backgrounds/
mate-background-properties/ubuntu-mate-pink.xml /usr/share/mate-background-properties/
