name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: sudo apt-get install python3 librsvg2-bin imagemagick debhelper pylint3

    - name: Clone ubuntu-mate-artwork
      run: git clone https://github.com/ubuntu-mate/ubuntu-mate-artwork.git --depth=1

    - name: Analyse Python Script
      run: ./scripts/lint.sh

    - name: Test Build of Ambiant-MATE
      run: ./ubuntu-mate-colours-generator --ignore-existing --install-icon-dir=usr/share/icons --install-theme-dir=usr/share/themes --src-dir=ubuntu-mate-artwork/ --theme="Ambiant-MATE" --hex="#2DACD4" --name="Aqua-Test" --tweaks=mono-osd-icons

    - name: Test Build of Ambiant-MATE-Dark
      run: ./ubuntu-mate-colours-generator --ignore-existing --install-icon-dir=usr/share/icons --install-theme-dir=usr/share/themes --src-dir=ubuntu-mate-artwork/ --theme="Ambiant-MATE-Dark" --hex="#2DACD4"  --name="Aqua-Test" --tweaks=mono-osd-icons

    - name: Test Build of Radiant-MATE
      run: ./ubuntu-mate-colours-generator --ignore-existing --install-icon-dir=usr/share/icons --install-theme-dir=usr/share/themes --src-dir=ubuntu-mate-artwork/ --theme="Radiant-MATE" --hex="#2DACD4" --name="Aqua-Test" --tweaks=mono-osd-icons

    - name: Test Build of Source Package
      run: |
        sed -i "s#) focal#-UNRELEASED) focal#g" debian/changelog
        dpkg-buildpackage -S -us -uc -d
        lintian --suppress-tags bad-distribution-in-changes-file
