name: Test Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3 librsvg2-bin imagemagick
        sudo apt-get install meson sassc libglib2.0-bin libgtk-3-dev inkscape optipng ruby x11-apps
        sudo apt-get install debhelper pylint3 lintian

    - name: Check Python script for errors
      run: ./scripts/lint.sh

    - name: Clone ubuntu-mate-artwork
      run: git clone https://github.com/ubuntu-mate/ubuntu-mate-artwork.git --depth=1

    - name: Clone Yaru-MATE
      run: |
        git clone https://github.com/ubuntu/yaru.git -b hirsute/mate --depth=1 yaru-src
        rm -rf yaru-src/.github/

    - name: Test Build of Ambiant-MATE
      run: ./generate-ambiant-mate-colour.py --ignore-existing --install-icon-dir=usr/share/icons --install-theme-dir=usr/share/themes --src-dir=ubuntu-mate-artwork/ --theme="Ambiant-MATE" --hex="#2DACD4" --name="Aqua" --tweaks=mono-osd-icons

    - name: Test Build of Ambiant-MATE-Dark
      run: ./generate-ambiant-mate-colour.py --ignore-existing --install-icon-dir=usr/share/icons --install-theme-dir=usr/share/themes --src-dir=ubuntu-mate-artwork/ --theme="Ambiant-MATE-Dark" --hex="#CE3A3A"  --name="Red"

    - name: Test Build of Radiant-MATE
      run: ./generate-ambiant-mate-colour.py --ignore-existing --install-icon-dir=usr/share/icons --install-theme-dir=usr/share/themes --src-dir=ubuntu-mate-artwork/ --theme="Radiant-MATE" --hex="#DFCA25" --name="Yellow" --tweaks=mono-osd-icons,black-selected-text

    - name: Test Build of Yaru-MATE
      run: ./generate-yaru-mate-colour.py --hex "#2DACD4" --name "Aqua" --src-dir yaru-src --usr-dir=usr/

    - name: Test Build of Source Package
      run: |
        dpkg-buildpackage -S -us -uc -d
        lintian --suppress-tags bad-distribution-in-changes-file
