name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: sudo apt-get install python3 librsvg2-bin imagemagick

    - name: Clone ubuntu-mate-artwork
      run: git clone https://github.com/ubuntu-mate/ubuntu-mate-artwork.git --depth=1

    - name: Test Build of Ambiant-MATE
      run: >-
        ./ubuntu-mate-colours-generator \
        --install-icon-dir=usr/share/icons \
        --install-theme-dir=usr/share/themes \
        --src-dir=ubuntu-mate-artwork/ \
        --theme="Ambiant-MATE" \
        --hex="#2DACD4" \
        --name="Aqua-Test"

    - name: Test Build of Ambiant-MATE-Dark
      run: >-
        ./ubuntu-mate-colours-generator \
        --install-icon-dir=usr/share/icons \
        --install-theme-dir=usr/share/themes \
        --src-dir=ubuntu-mate-artwork/ \
        --theme="Ambiant-MATE-Dark" \
        --hex="#2DACD4" \
        --name="Aqua-Test"

    - name: Test Build of Radiant-MATE
      run: >-
        ./ubuntu-mate-colours-generator \
        --install-icon-dir=usr/share/icons \
        --install-theme-dir=usr/share/themes \
        --src-dir=ubuntu-mate-artwork/ \
        --theme="Radiant-MATE" \
        --hex="#2DACD4" \
        --name="Aqua-Test"
