name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3 pylint3 librsvg2-bin imagemagick

    - name: Check Python script for errors
      run: ./scripts/lint.sh

    - name: Clone Ambiant-MATE
      run: git clone https://github.com/lah7/Ambiant-MATE.git --depth=1 src

    - name: Test Build of Ambiant-MATE
      run: ./generate-ambiant-mate-colour.py --ignore-existing --install-icon-dir=usr/share/icons --install-theme-dir=usr/share/themes --src-dir=src/ --theme="Ambiant-MATE" --hex="#2DACD4" --name="Aqua" --tweaks=mono-osd-icons

    - name: Test Build of Ambiant-MATE-Dark
      run: ./generate-ambiant-mate-colour.py --ignore-existing --install-icon-dir=usr/share/icons --install-theme-dir=usr/share/themes --src-dir=src/ --theme="Ambiant-MATE-Dark" --hex="#CE3A3A"  --name="Red"

    - name: Test Build of Radiant-MATE
      run: ./generate-ambiant-mate-colour.py --ignore-existing --install-icon-dir=usr/share/icons --install-theme-dir=usr/share/themes --src-dir=src/ --theme="Radiant-MATE" --hex="#DFCA25" --name="Yellow" --tweaks=mono-osd-icons,black-selected-text

  package:
    name: Test Packaging
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install debhelper lintian

    - name: Test Build of Source Package
      run: |
        dpkg-buildpackage -S -us -uc -d
        lintian --suppress-tags bad-distribution-in-changes-file
